inputJarPath = "E:/XiangMu/JavaShroud-public/promo-video-v2/demo-artifacts/build/dist/demo-baseline.jar"
outputJarPath = "E:/XiangMu/JavaShroud-public/promo-video-v2/demo-artifacts/build/protected/demo-protected.jar"
allowOptInPasses = true
allowIncomplete = false
allowRedundantPasses = false

[[passes]]
id = "string-encryption"
enabled = true
[passes.params]
decoderBackend = "native-kernel"
scope = "all-strings"
strength = "max"
payloadCodec = "auto"

[[passes]]
id = "control-flow-obfuscation"
enabled = true
[passes.params]
branchInjection = "normal"
handlerSplit = "none"
density = 8
dispatchMode = "tableswitch-hybrid"
algebraicFamily = "mixed"

[[passes]]
id = "jni-microkernel-loader"
enabled = true
[passes.params]
kernelComponents = "vm"
targetPlatform = "windows-x64,linux-x64"
nativeRecompilation = true
nativePackingLevel = "max"

[[passes]]
id = "method-virtualization"
enabled = true
[passes.params]
methodSelection = "safe"
strictVirtualization = true
maxInstructions = 99999
maxBroadVirtualizedMethods = 99999

[ruleSet]
rules = []

[[passSelections]]
passId = "string-encryption"
mode = "selected-only"
[[passSelections.rules]]
target = "demo/MessageVault"
action = "obfuscate"

[[passSelections]]
passId = "control-flow-obfuscation"
mode = "selected-only"
[[passSelections.rules]]
target = "demo/AccessPolicy"
action = "obfuscate"

[[passSelections]]
passId = "jni-microkernel-loader"
mode = "selected-only"
[[passSelections.rules]]
target = "demo/Main"
action = "obfuscate"

[[passSelections]]
passId = "method-virtualization"
mode = "selected-only"
[[passSelections.rules]]
target = "demo/ProtectedOperation#execute:(II)J"
action = "obfuscate"
