[package]
name = "qp-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
qp-crypto.workspace = true
qp-page.workspace = true
qp-runtime.workspace = true
qp-vm.workspace = true

[dev-dependencies]
qp-shell.workspace = true

[lints]
workspace = true
