// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelObfuscation() {
  return window['go']['main']['App']['CancelObfuscation']();
}

export function GetEngineCapabilities() {
  return window['go']['main']['App']['GetEngineCapabilities']();
}

export function InspectJarClasses(arg1) {
  return window['go']['main']['App']['InspectJarClasses'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SelectExportConfig() {
  return window['go']['main']['App']['SelectExportConfig']();
}

export function SelectImportConfig() {
  return window['go']['main']['App']['SelectImportConfig']();
}

export function SelectInputJar() {
  return window['go']['main']['App']['SelectInputJar']();
}

export function SelectOutputJar(arg1) {
  return window['go']['main']['App']['SelectOutputJar'](arg1);
}

export function StartObfuscation(arg1) {
  return window['go']['main']['App']['StartObfuscation'](arg1);
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
