// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelObfuscation():Promise<void>;

export function GetEngineCapabilities():Promise<string>;

export function InspectJarClasses(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SelectExportConfig():Promise<string>;

export function SelectImportConfig():Promise<string>;

export function SelectInputJar():Promise<string>;

export function SelectOutputJar(arg1:string):Promise<string>;

export function StartObfuscation(arg1:main.ObfuscationRequest):Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
